run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign

issues:
  exclude-use-default: false
  max-same-issues: 5
  max-issues-per-linter: 0
