// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package buffers

import "strconv"

type ClientMessageType uint16

const (
	ClientMessageTypePING_SUCCESS          ClientMessageType = 0
	ClientMessageTypeSESSION_START_SUCCESS ClientMessageType = 1
	ClientMessageTypeSESSION_START_FAILED  ClientMessageType = 2
	ClientMessageTypeSESSION_END_SUCCESS   ClientMessageType = 3
	ClientMessageTypeSESSION_END_FAILED    ClientMessageType = 4
	ClientMessageTypeEVENT_SUCCESS         ClientMessageType = 5
	ClientMessageTypeEVENT_FAILED          ClientMessageType = 6
	ClientMessageTypeNOTIFICATION          ClientMessageType = 7
)

var EnumNamesClientMessageType = map[ClientMessageType]string{
	ClientMessageTypePING_SUCCESS:          "PING_SUCCESS",
	ClientMessageTypeSESSION_START_SUCCESS: "SESSION_START_SUCCESS",
	ClientMessageTypeSESSION_START_FAILED:  "SESSION_START_FAILED",
	ClientMessageTypeSESSION_END_SUCCESS:   "SESSION_END_SUCCESS",
	ClientMessageTypeSESSION_END_FAILED:    "SESSION_END_FAILED",
	ClientMessageTypeEVENT_SUCCESS:         "EVENT_SUCCESS",
	ClientMessageTypeEVENT_FAILED:          "EVENT_FAILED",
	ClientMessageTypeNOTIFICATION:          "NOTIFICATION",
}

var EnumValuesClientMessageType = map[string]ClientMessageType{
	"PING_SUCCESS":          ClientMessageTypePING_SUCCESS,
	"SESSION_START_SUCCESS": ClientMessageTypeSESSION_START_SUCCESS,
	"SESSION_START_FAILED":  ClientMessageTypeSESSION_START_FAILED,
	"SESSION_END_SUCCESS":   ClientMessageTypeSESSION_END_SUCCESS,
	"SESSION_END_FAILED":    ClientMessageTypeSESSION_END_FAILED,
	"EVENT_SUCCESS":         ClientMessageTypeEVENT_SUCCESS,
	"EVENT_FAILED":          ClientMessageTypeEVENT_FAILED,
	"NOTIFICATION":          ClientMessageTypeNOTIFICATION,
}

func (v ClientMessageType) String() string {
	if s, ok := EnumNamesClientMessageType[v]; ok {
		return s
	}
	return "ClientMessageType(" + strconv.FormatInt(int64(v), 10) + ")"
}
