// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package buffers

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ClientMessagePacketT struct {
	CorrelationId []byte `json:"correlation_id"`
	Type ClientMessageType `json:"type"`
	Length uint16 `json:"length"`
	Body []byte `json:"body"`
}

func (t *ClientMessagePacketT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	correlationIdOffset := flatbuffers.UOffsetT(0)
	if t.CorrelationId != nil {
		correlationIdOffset = builder.CreateByteString(t.CorrelationId)
	}
	bodyOffset := flatbuffers.UOffsetT(0)
	if t.Body != nil {
		bodyOffset = builder.CreateByteString(t.Body)
	}
	ClientMessagePacketStart(builder)
	ClientMessagePacketAddCorrelationId(builder, correlationIdOffset)
	ClientMessagePacketAddType(builder, t.Type)
	ClientMessagePacketAddLength(builder, t.Length)
	ClientMessagePacketAddBody(builder, bodyOffset)
	return ClientMessagePacketEnd(builder)
}

func (rcv *ClientMessagePacket) UnPackTo(t *ClientMessagePacketT) {
	t.CorrelationId = rcv.CorrelationIdBytes()
	t.Type = rcv.Type()
	t.Length = rcv.Length()
	t.Body = rcv.BodyBytes()
}

func (rcv *ClientMessagePacket) UnPack() *ClientMessagePacketT {
	if rcv == nil {
		return nil
	}
	t := &ClientMessagePacketT{}
	rcv.UnPackTo(t)
	return t
}

type ClientMessagePacket struct {
	_tab flatbuffers.Table
}

func GetRootAsClientMessagePacket(buf []byte, offset flatbuffers.UOffsetT) *ClientMessagePacket {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ClientMessagePacket{}
	x.Init(buf, n+offset)
	return x
}

func FinishClientMessagePacketBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsClientMessagePacket(buf []byte, offset flatbuffers.UOffsetT) *ClientMessagePacket {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ClientMessagePacket{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedClientMessagePacketBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ClientMessagePacket) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ClientMessagePacket) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ClientMessagePacket) CorrelationId(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ClientMessagePacket) CorrelationIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ClientMessagePacket) CorrelationIdBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClientMessagePacket) MutateCorrelationId(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func (rcv *ClientMessagePacket) Type() ClientMessageType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return ClientMessageType(rcv._tab.GetUint16(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ClientMessagePacket) MutateType(n ClientMessageType) bool {
	return rcv._tab.MutateUint16Slot(6, uint16(n))
}

func (rcv *ClientMessagePacket) Length() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ClientMessagePacket) MutateLength(n uint16) bool {
	return rcv._tab.MutateUint16Slot(8, n)
}

func (rcv *ClientMessagePacket) Body(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *ClientMessagePacket) BodyLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ClientMessagePacket) BodyBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ClientMessagePacket) MutateBody(j int, n byte) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.MutateByte(a+flatbuffers.UOffsetT(j*1), n)
	}
	return false
}

func ClientMessagePacketStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func ClientMessagePacketAddCorrelationId(builder *flatbuffers.Builder, correlationId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(correlationId), 0)
}
func ClientMessagePacketStartCorrelationIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ClientMessagePacketAddType(builder *flatbuffers.Builder, type_ ClientMessageType) {
	builder.PrependUint16Slot(1, uint16(type_), 0)
}
func ClientMessagePacketAddLength(builder *flatbuffers.Builder, length uint16) {
	builder.PrependUint16Slot(2, length, 0)
}
func ClientMessagePacketAddBody(builder *flatbuffers.Builder, body flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(body), 0)
}
func ClientMessagePacketStartBodyVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func ClientMessagePacketEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
